use_frameworks!

platform :ios, '9.0'

target 'LQTool_Example' do
  pod 'LQTool', :path => '../'

  target 'LQTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
